export const CLAIM_STATUS = {
  DRAFT: "DRAFT",
  PENDING_MANAGER: "PENDING_MANAGER",
  PENDING_SENIOR_MANAGER: "PENDING_SENIOR_MANAGER",
  REVERTED_TO_MANAGER: "REVERTED_TO_MANAGER",
  REVERTED_TO_EMPLOYEE: "REVERTED_TO_EMPLOYEE",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
} as const;